title: Nghi Huynh
description: Hi, I'm Nghi Huynh. I'm a McGill graduate with a bachelor's in Computer Science and Biology and a minor in Mathematics. I'm interested in data science, especially the applications of deep learning in the healthcare domain.
theme: jekyll-theme-minimal
